server:
  port: 8082

spring:
  application:
    name: catalog-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.1.151:5432/helium}
    username: ${SPRING_DATASOURCE_USERNAME:heliumUser}
    password: ${SPRING_DATASOURCE_PASSWORD:heliumPassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:192.168.1.151}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,trace
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    dev.portero.helium.catalog: DEBUG
