server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:192.168.1.151}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        register: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: catalog
              uri: lb://catalog-service
              predicates:
                - Path=/catalog/**
            - id: client
              uri: lb://client-service
              predicates:
                - Path=/client/**
